### ISSUE TITLE
Youtube video's author name?

### ISSUE THREAD

**Issue by Aida-Enna** [thisistorsten/YouTubeApiSharp#2]
Is there any way to use this library to get the creator's name of a YouTube video? Preferably a unique ID like the ChannelName but Display Name would be better than nothing. Thank you!

**Comment by iamtorsten** [comment]
Like this? https://github.com/snakx/YouTubeApiSharp/blob/main/src/YouTubeApiSharp/YouTubeApiSharp/API/VideoSearch.cs#L64

**Comment by Aida-Enna** [comment]
I see that, but I don't know how to access it based on the example you gave on the front page.

```csharp
IEnumerable<VideoInfo> videoInfos = DownloadUrlResolver.GetDownloadUrls(URL.Value);

string Author = videoInfos.First().???
```

Is there documentation for accessing the "VideoSearch" object?

**Comment by thisistorsten** [comment]
https://github.com/snakx/YouTubeApiSharp/blob/main/src/ExampleApplication/Program.cs#L38

**Comment by Aida-Enna** [comment]
Ah, I didn't realize there was examples, sorry! This works great, thank you!

**Comment by iamtorsten** [comment]
You are welcome ☺️👍🏻

Aida Enna ***@***.***> schrieb am Mi., 23. Juni 2021, 19:14:
